#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jaraco.text
Version  : 3.5.1
Release  : 14
URL      : https://files.pythonhosted.org/packages/53/d2/40ff557369eccee312b2d3ff4cb97373e8ffb25afb92294ff650a1e45795/jaraco.text-3.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/53/d2/40ff557369eccee312b2d3ff4cb97373e8ffb25afb92294ff650a1e45795/jaraco.text-3.5.1.tar.gz
Summary  : Module for text manipulation
Group    : Development/Tools
License  : MIT
Requires: jaraco.text-license = %{version}-%{release}
Requires: jaraco.text-python = %{version}-%{release}
Requires: jaraco.text-python3 = %{version}-%{release}
Requires: jaraco.functools
BuildRequires : buildreq-distutils3
BuildRequires : jaraco.functools
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/jaraco.text.svg
:target: `PyPI link`_
.. image:: https://img.shields.io/pypi/pyversions/jaraco.text.svg
:target: `PyPI link`_

%package license
Summary: license components for the jaraco.text package.
Group: Default

%description license
license components for the jaraco.text package.


%package python
Summary: python components for the jaraco.text package.
Group: Default
Requires: jaraco.text-python3 = %{version}-%{release}

%description python
python components for the jaraco.text package.


%package python3
Summary: python3 components for the jaraco.text package.
Group: Default
Requires: python3-core
Provides: pypi(jaraco.text)
Requires: pypi(jaraco.functools)

%description python3
python3 components for the jaraco.text package.


%prep
%setup -q -n jaraco.text-3.5.1
cd %{_builddir}/jaraco.text-3.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629183207
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jaraco.text
cp %{_builddir}/jaraco.text-3.5.1/LICENSE %{buildroot}/usr/share/package-licenses/jaraco.text/8e6689d37f82d5617b7f7f7232c94024d41066d1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.*/site-packages/jaraco/__init__.py
rm -f %{buildroot}/usr/lib/python3.*/site-packages/jaraco/__pycache__/__init__.*

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jaraco.text/8e6689d37f82d5617b7f7f7232c94024d41066d1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
